### PR TITLE
Support for secret scanning alerts

### PR DESCRIPTION
**Pull request by zbazztian**
This PR makes the action also synchronize secret scanning alerts.

Note that the secret scanning api only allows fetching secret alerts from private repositories. For public repositories, we just assume an empty result list.

To achieve this, I had to refactor parts of `ghlib.py` and change the format of the state files (files with the old format will be automatically converted). I took some care to not disturb existing synchronization projects, but would be happy to hear about cases were this PR impacts existing projects negatively.

I'll give this a bit more testing, but wanted to put it out here for initial thoughts.

@cmboling

### CODE REVIEW

**Comment by cmboling** [comment]
I got some time to buckle down on testing this Thursday and Friday! Just skimmed thru the changes and looks good so far. I'll update you here by end of Friday (PST).

**Comment by zbazztian** [comment]
Awesome, appreciate it! I am still working on the webhook parts for this, so it's probably best to wait with testing until this PR is complete, though. I'll update this soon. Cheers!

**Comment by cmboling** [comment]
I'm planning to refactor this after releasing the breaking changes here: https://github.com/github/codescanning-jira-integration/issues/16

**Comment by cmboling** [comment]
Resolved conflicts; need to do thorough testing of this:

- [ ] We can sync secret scanning alerts and update code scanning alerts like usual
- [ ] We can sync updated secret scanning alerts, as well as update code scanning alerts like usual
- [ ] We can successfully add integration to a new repo and sync alerts and satisfy the above two criteria as well

**Comment by zbazztian** [comment]
Thanks @cmboling ! I'll see whether I can test this, but it would likely be next week.

**Comment by cmboling** [comment]
@zbazztian tested this pretty thoroughly! LGTM. 👍🏼

**Review by Kokeykokey — CHANGES_REQUESTED** [review]
#

**Comment by zbazztian** [comment]
@cmboling Looks good to me. Did we ever think about having versioned branches? I guess currently people are using the action off of the main branch, so perhaps we should at some point transition to having `v1`, `v2`, ... branches / tags, to make this more stable, especially when we introduce major features like this.
However, due to lack of time, I'll merge this for now. Thanks for bringing this back to life!

**Comment by cmboling** [comment]
Hey @zbazztian! Just got back from OOO a few days ago! Thanks for merging. At the moment I've been moving the v1 branch up to main; I thought about making the `v2` branch to have the secret scanning alerts, but that would mean users will have to submit another set of changes to take advantage of a new branch. If we make other significant changes from this point forward, let's make that the `v2` branch. 👍🏼

**Pull request merged**
